search:
  type: "search"
  target: "GATEWAY"
  executed: false
  shouldRender: true
  config: "search"
  nextRequest: "on_search"
  preRequest: null
  isCollapsed: false

on_search:
  type: "on_search"
  executed: false
  shouldRender: false
  config: "on_search"
  nextRequest: "personal_info_form"
  preRequest: "search"
  isCollapsed: false

personal_info_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "personal_info_form"
  nextRequest: "select_loan"
  preRequest: "on_search"
  isCollapsed: false

select_loan:
  type: "select"
  target: "NP"
  executed: false
  shouldRender: false
  config: "select_loan"
  nextRequest: "on_select_loan"
  preRequest: "personal_info_form"
  isCollapsed: false

on_select_loan:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select_loan"
  nextRequest: select_approval
  preRequest: "select_loan"
  isCollapsed: false

select_approval:
  type: "select"
  target: "NP"
  executed: false
  shouldRender: false
  config: "select_approval"
  nextRequest: "on_select_approval"
  preRequest: "on_select_loan"
  isCollapsed: false

on_select_approval:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select_approval"
  nextRequest: loan_amount_adjust_form
  preRequest: "select_approval"
  isCollapsed: false

loan_amount_adjust_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "loan_amount_adjust_form"
  nextRequest: select_after_amount_adjust
  preRequest: "on_select_approval"
  isCollapsed: false

select_after_amount_adjust:
  type: "select"
  target: "NP"
  executed: false
  shouldRender: false
  config: "select_after_amount_adjust"
  nextRequest: "on_select_after_amount_adjust"
  preRequest: "loan_amount_adjust_form"
  isCollapsed: false

on_select_after_amount_adjust:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select_after_amount_adjust"
  nextRequest: kyc_form
  preRequest: "select_after_amount_adjust"
  isCollapsed: false

kyc_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "kyc_form"
  nextRequest: init_kyc
  preRequest: "on_select_after_amount_adjust"
  isCollapsed: false

init_kyc:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init_kyc"
  nextRequest: on_init_kyc
  preRequest: "kyc_form"
  isCollapsed: false

on_init_kyc:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init_kyc"
  nextRequest: account_details_form
  preRequest: "init_kyc"
  isCollapsed: false

account_details_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "account_details_form"
  nextRequest: init_personal_loan
  preRequest: "on_init_kyc"
  isCollapsed: false

init_personal_loan:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init_personal_loan"
  nextRequest: on_init_personal_loan
  preRequest: "account_details_form"
  isCollapsed: false

on_init_personal_loan:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init_personal_loan"
  nextRequest: e_mandate_details_form
  preRequest: "init_personal_loan"
  isCollapsed: false

e_mandate_details_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "e_mandate_details_form"
  nextRequest: init_with_account_details
  preRequest: "on_init_personal_loan"
  isCollapsed: false

init_with_account_details:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init_with_account_details"
  nextRequest: on_init_with_account_details
  preRequest: "e_mandate_details_form"
  isCollapsed: false

on_init_with_account_details:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init_with_account_details"
  nextRequest: loan_agreement_form
  preRequest: "init_with_account_details"
  isCollapsed: false

loan_agreement_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "loan_agreement_form"
  nextRequest: confirm
  preRequest: "on_init_with_account_details"
  isCollapsed: false

confirm:
  type: "confirm"
  target: "NP"
  executed: false
  shouldRender: false
  config: "confirm"
  nextRequest: on_confirm
  preRequest: "loan_agreement_form"
  isCollapsed: false

on_confirm:
  type: "on_confirm"
  executed: false
  shouldRender: false
  config: "on_confirm"
  nextRequest: update
  preRequest: "confirm"
  isCollapsed: false

update:
  type: "update"
  target: "NP"
  executed: false
  shouldRender: false
  config: "update"
  nextRequest: on_update
  preRequest: "on_confirm"
  isCollapsed: false

on_update:
  type: "on_update"
  executed: false
  shouldRender: false
  config: "on_update"
  nextRequest: status
  preRequest: "update"
  isCollapsed: false

status:
  type: "status"
  target: "NP"
  executed: false
  shouldRender: false
  config: "status"
  nextRequest: on_status
  preRequest: "on_update"
  isCollapsed: false

on_status:
  type: "on_status"
  executed: false
  shouldRender: false
  config: "on_status"
  nextRequest: null
  preRequest: "status"
  isCollapsed: false
