# filename = output json name
# domain = path argument
# path = data read from configs

configs:
  - filename: trv_build.json
    domain: trv
    path:
      $ref: ./TRV/index.yaml
  - filename: fis_build.json
    domain: fis
    path:
      $ref: ./FIS/index.yaml
