flows:
  - summary: Personal Loan [2.0.0]
    id: personal-loan-flow-1
    shouldDispaly: true
    input:
      $ref: ./personal-loan-flow-1/input.yaml
    calls:
      $ref: ./personal-loan-flow-1/protocolCalls.yaml
