flows:
  - summary: Personal Loan [2.0.0]
    id: personal-loan-flow-1
    shouldDispaly: true
    input:
      $ref: ./personal-loan-flow-1/input.yaml
    calls:
      $ref: ./personal-loan-flow-1/protocolCalls.yaml
  - summary: Marine Insurance
    id: marine-insurance-flow-1
    shouldDispaly: true
    input:
      $ref: ./marine-insurance-flow-1/input.yaml
    calls:
      $ref: ./marine-insurance-flow-1/protocolCalls.yaml
  - summary: Invoice Based Loans
    id: invoice-loan-flow-1
    shouldDispaly: true
    input:
      $ref: ./invoice-loan-flow-1/input.yaml
    calls:
      $ref: ./invoice-loan-flow-1/protocolCalls.yaml
    additionalFlows:
      - key: Missed-EMI Payment
        value: invoice-loan-missed-emi-flow-1
  - summary: Missed-EMI Payment
    id: invoice-loan-missed-emi-flow-1
    shouldDispaly: false
    input:
      $ref: ./invoice-loan-missed-emi-flow-1/input.yaml
    calls:
      $ref: ./invoice-loan-missed-emi-flow-1/protocolCalls.yaml
