flows:
  - summary: Metro - Station Code Based Flow
    id: metro-flow-1
    shouldDispaly: true
    input:
      $ref: ./metro-flow-1/input.yaml
    calls:
      $ref: ./metro-flow-1/protocolCalls.yaml

  - summary: IntraCity - Code Based Flow
    id: intracity-flow-1
    shouldDispaly: true
    input:
      $ref: ./intracity-flow-1/input.yaml
    calls:
      $ref: ./intracity-flow-1/protocolCalls.yaml

  - summary: InterCity(Bus) - Station Code Based Flow
    id: intercity-flow-1
    shouldDispaly: true
    input:
      $ref: ./intercity-flow-1/input.yaml
    calls:
      $ref: ./intercity-flow-1/protocolCalls.yaml
