flows: 
  - summary: message.intent.fulfillment.vehicle.category
    id: metro-flow-1
    shouldDispaly: true
    sessionData:
      additionalFlowStartPoint: update
      additionalFlowActive: false
    input:
      $ref: ./metro/input.yaml
    calls:
      $ref: ./metro/protocolCalls.yaml
