flows:
  - summary: Metro - Station Code Based Flow
    id: metro-flow-1
    shouldDispaly: true
    input:
      $ref: ./metro-flow-1/input.yaml
    calls:
      $ref: ./metro-flow-1/protocolCalls.yaml
