flows:
  - summary: IntraCity - Code Based Flow
    id: intracity-flow-1
    shouldDispaly: true
    input:
      $ref: ./intracity-flow-1/input.yaml
    calls:
      $ref: ./intracity-flow-1/protocolCalls.yaml
