flows: 
  - summary: Metro
    id: metro-station-based-flow
    shouldDispaly: true
    sessionData:
      additionalFlowStartPoint: update
      additionalFlowActive: false
    input:
      $ref: ./metro/input.yaml
    calls:
      $ref: ./metro/protocolCalls.yaml
