search:
  - name: "Insurance Category"
    key: "insuranceCategaory"
    type: "text"
    errorText: "Insurance Category is required"
    required: true
    summary: This attribute refers to categorizing loans based on whether they are intended for personal use or are meant for invoices.
  - name: "Payment Tags"
    key: "paymentTagsSearch"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        BUYER_FINDER_FEES_TYPE: percent-annualized
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        DELAY_INTEREST: 2.5
        STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
    errorText: "Payment tags is required"
    required: true
    summary: Describes tags

personal_info_form:
  - name: "BPP URI"
    key: "bpp_uri"
    type: "select"
    extractionPath: "businessPayload[]{key: bpp_uri, value: bpp_uri}"
    errorText: "BPP URI is required"
    required: true
    summary: The subscriber URL of the Seller App (BPP) is the endpoint that accepts callbacks from the Buyer App (BAP).
  - name: "BPP ID"
    key: "bpp_id"
    type: "select"
    extractionPath: "businessPayload[]{key: bpp_id, value: bpp_id}"
    errorText: "BPP ID is required"
    required: true
    summary: It explains the Explains the subscriber of the Seller App (BPP).
  - name: Form Url
    key: personalFormUrl
    type: "form"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].formData[]{key: formUrl, value: formUrl}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    summary: Need to be filled to get the submission id
  - name: "ProviderId"
    key: "providerId"
    type: "select"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].formData[]{key: providerId, value: providerId}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    errorText: "Provider Id is required"
    required: true
    summary: This refers to the unique id of the provider whose catalog items have been selected.
  - name: "Form Id"
    key: "formId"
    type: "select"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].formData[]{key: id, value: id}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller
  - name: "Item Id"
    key: "itemId"
    type: "select"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].formData[]{key: itemId, value: itemId}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    errorText: "item Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

select_1:
  - name: Submission ID
    key: personalInfoSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission

additional_info_form:
  - name: Form Url
    key: additionalInfoFormUrl
    type: "form"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].formData[]{key: formUrl, value: formUrl}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    summary: Need to be filled to get the submission id
  - name: "Form Id"
    key: "formIdAdditionalInfo"
    type: "select"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].formData[]{key: id, value: id}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

select_2:
  - name: Submission ID
    key: additionalInfoSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission

ekyc_form:
  - name: Form Url
    key: ekycFormUrl
    type: "form"
    extractionPath: "businessPayload[].formData[]{key: formUrl, value: formUrl}"
    summary: Need to be filled to get the submission id
  - name: "Form Id"
    key: "ekycFormId"
    type: "select"
    extractionPath: "businessPayload[].formData[]{key: id, value: id}"
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

init:
  - name: Submission ID
    key: ekycSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission
  - name: "Payment Status"
    key: "paymentStatus"
    type: "select"
    defaultOptions:
      - key: "PAID"
        value: "PAID"
      - key: "NOT-PAID"
        value: "NOT-PAID"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Type"
    key: "paymentType"
    type: "select"
    defaultValue: "PRE-ORDER"
    defaultOptions:
      - key: "PRE-ORDER"
        value: "PRE-ORDER"
      - key: "PRE-FULFILLMENT"
        value: "PRE-FULFILLMENT"
      - key: "ON-FULFILLMENT"
        value: "ON-FULFILLMENT"
      - key: "POST-FULFILLMENT"
        value: "POST-FULFILLMENT"
      - key: "ON-ORDER"
        value: "ON-ORDER"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Tags"
    key: "paymentTagsInit"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        BUYER_FINDER_FEES_TYPE: percent-annualized
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        DELAY_INTEREST: 2.5
        STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
    errorText: "Payment Tags is required"
    required: true
    summary: Starting stop of the journey location

confirm:
  - name: "Payment Status"
    key: "paymentStatusConfirm"
    type: "select"
    defaultOptions:
      - key: "PAID"
        value: "PAID"
      - key: "NOT-PAID"
        value: "NOT-PAID"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Type"
    key: "paymentTypeConfirm"
    type: "select"
    defaultValue: "PRE-ORDER"
    defaultOptions:
      - key: "PRE-ORDER"
        value: "PRE-ORDER"
      - key: "PRE-FULFILLMENT"
        value: "PRE-FULFILLMENT"
      - key: "ON-FULFILLMENT"
        value: "ON-FULFILLMENT"
      - key: "POST-FULFILLMENT"
        value: "POST-FULFILLMENT"
      - key: "ON-ORDER"
        value: "ON-ORDER"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
