search:
  type: "search"
  target: "GATEWAY"
  executed: false
  shouldRender: true
  config: "search"
  nextRequest: "on_search"
  preRequest: null
  isCollapsed: false

on_search:
  type: "on_search"
  executed: false
  shouldRender: false
  config: "on_search"
  nextRequest: "personal_info_form"
  preRequest: "search"
  isCollapsed: false

personal_info_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "personal_info_form"
  nextRequest: "select_1"
  preRequest: "on_search"
  isCollapsed: false

select_1:
  type: "select"
  target: "NP"
  executed: false
  shouldRender: false
  config: "select_1"
  nextRequest: "on_select_1"
  preRequest: "personal_info_form"
  isCollapsed: false

on_select_1:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select_1"
  nextRequest: additional_info_form
  preRequest: "select_1"
  isCollapsed: false

additional_info_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "additional_info_form"
  nextRequest: select_2
  preRequest: "on_select_1"
  isCollapsed: false

select_2:
  type: "select"
  target: "NP"
  executed: false
  shouldRender: false
  config: "select_2"
  nextRequest: "on_select_2"
  preRequest: "additional_info_form"
  isCollapsed: false

on_select_2:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select_2"
  nextRequest: ekyc_form
  preRequest: "select_2"
  isCollapsed: false

ekyc_form:
  type: "form"
  executed: false
  shouldRender: false
  config: "ekyc_form"
  nextRequest: init
  preRequest: "on_select_2"
  isCollapsed: false

init:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init"
  nextRequest: on_init
  preRequest: "ekyc_form"
  isCollapsed: false

on_init:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init"
  nextRequest: confirm
  preRequest: "init"
  isCollapsed: false

confirm:
  type: "confirm"
  target: "NP"
  executed: false
  shouldRender: false
  config: "confirm"
  nextRequest: on_confirm
  preRequest: "on_init"
  isCollapsed: false

on_confirm:
  type: "on_confirm"
  executed: false
  shouldRender: false
  config: "on_confirm"
  nextRequest: null
  preRequest: "confirm"
  isCollapsed: false
