search:
  - name: "Vehicle Category"
    key: "VehicleCategaory"
    type: "text"
    errorText: "Vehicle category is required"
    defaultValue: METRO
    required: true
    summary: This attribute refers to categorizing loans based on whether they are intended for personal use or are meant for invoices.
  - name: "Payment Tags"
    key: "paymentTagsSearch"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        display: false
        BUYER_FINDER_FEES_TYPE: percent-annualized
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        display: false
        DELAY_INTEREST: 2.5
        STATIC_TERMS: ""
        OFFLINE_CONTRACT: "true"
    errorText: "Payment tags is required"
    required: true
    summary: Describes tags

search_1:
  - name: "Station Code 1"
    key: StationCode1IsRequired
    type: "text"
    errorText: "Station 1 is required"
    required: true
    summary: Station 1 is required
  - name: "Station Code 2"
    key: StationCode2IsRequired
    type: "text"
    errorText: "Station 2 is required"
    required: true
    summary: Station 2 is required 
select:
  - name: Catagory ID
    # key: CatagoryId #itemId
    type: "text"
    errorText: "Catagory Id is required"
    required: true
    summary: Catagory Id revieved from the provider
  - name: Quantity 
    key: Quantity Of Ticket
    type: "number"
    errorText: "Quantity is required"
    required: true
    summary: Quantity  revieved from the provider        
init :
   - name: Provider ID
     key: ProviderId 
     type: "text"
     errorText: "Provider Id is required"
     required: true
     summary: Provider Id revieved from the provide
   - name: "Payment Status"
     key: "paymentStatus"
     type: "select"
     defaultOptions:
        - key: "PAID"
          value: "PAID"
        - key: "NOT-PAID"
          value: "NOT-PAID"
     errorText: "Please select a field"
     required: true
     summary: Starting stop of the journey location
   - name: "Payment Type"
     key: "paymentType"
     type: "select"
     defaultValue: "PRE-ORDER"
     defaultOptions:
        - key: "PRE-ORDER"
          value: "PRE-ORDER"
        - key: "PRE-FULFILLMENT"
          value: "PRE-FULFILLMENT"
        - key: "ON-FULFILLMENT"
          value: "ON-FULFILLMENT"
        - key: "POST-FULFILLMENT"
          value: "POST-FULFILLMENT"
        - key: "ON-ORDER"
          value: "ON-ORDER"
     errorText: "Please select a field"
     required: true
     summary: Starting stop of the journey location
   - name: "Payment Tags"
     key: "paymentTagsInit"
     type: "multiline"
     defaultValue:
        BUYER_FINDER_FEES:
          BUYER_FINDER_FEES_TYPE: percent-annualized
          BUYER_FINDER_FEES_PERCENTAGE: "1"
        SETTLEMENT_TERMS:
          DELAY_INTEREST: 2.5
          STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
     errorText: "Payment Tags is required"
     required: true
     summary: Starting stop of the journey location   
confirm:
  - name: "Payment Status"
    key: "paymentStatusConfirm"
    type: "select"
    defaultOptions:
      - key: "PAID"
        value: "PAID"
      - key: "NOT-PAID"
        value: "NOT-PAID"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Type"
    key: "paymentTypeConfirm"
    type: "select"
    defaultValue: "PRE-ORDER"
    defaultOptions:
      - key: "PRE-ORDER"
        value: "PRE-ORDER"
      - key: "PRE-FULFILLMENT"
        value: "PRE-FULFILLMENT"
      - key: "ON-FULFILLMENT"
        value: "ON-FULFILLMENT"
      - key: "POST-FULFILLMENT"
        value: "POST-FULFILLMENT"
      - key: "ON-ORDER"
        value: "ON-ORDER"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location 

update:
  - name: Order Id
    key: orderId
    type: "text"
    errorText: "Order Id is required"
    required: true
    summary: Order Id revieved after form submission
  - name: Order status
    key: fulfillmentStatus
    type: "select"
    defaultValue: "APPROVED"
    defaultOptions:
      - key: "APPROVED"
        value: "APPROVED"
    errorText: "Please select a field"
    required: true
    summary: Order status is the status of fulfillment

status:
  - name: Order Id
    key: orderId
    type: "text"
    errorText: "Order Id is required"
    required: true
    summary: Order Id revieved after form submission


