search:
  type: "search"
  target: "GATEWAY"
  executed: false
  shouldRender: true
  config: "search"
  nextRequest: "on_search"
  preRequest: null
  isCollapsed: true

on_search:
  type: "on_search"
  executed: false
  shouldRender: false
  config: "on_search"
  nextRequest: "search_1"
  preRequest: "search"
  isCollapsed: true 

search_1:
  type: "search"
  target: "NP"
  executed: false
  shouldRender: false
  config: "search_1"
  nextRequest: "on_search_1"
  preRequest: "on_search"
  isCollapsed: true

on_search_1:
  type: "on_search"
  executed: false
  shouldRender: false
  config: "on_search_1"
  nextRequest: select
  preRequest: "search_1"
  isCollapsed: true

select:
  type: "select"
  target: "NP"
  executed: false
  shouldRender: false
  config: "select"
  nextRequest: "on_select"
  preRequest: "on_search_1"
  isCollapsed: true

on_select:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select"
  nextRequest: init
  preRequest: "select"
  isCollapsed: true 

init:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init"
  nextRequest: on_init
  preRequest: "on_select"
  isCollapsed: true 

on_init:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init"
  nextRequest: confirm
  preRequest: "init"
  isCollapsed: true

confirm:
  type: "confirm"
  target: "NP"
  executed: false
  shouldRender: false
  config: "confirm"
  nextRequest: on_confirm
  preRequest: "on_init"
  isCollapsed: true

on_confirm:
  type: "on_confirm"
  executed: false
  shouldRender: false
  config: "on_confirm"
  nextRequest: status
  preRequest: "confirm"
  isCollapsed: true

# update:
#   type: "update"
#   target: "NP"
#   executed: false
#   shouldRender: false
#   config: "update"
#   nextRequest: on_update
#   preRequest: "on_confirm"
#   isCollapsed: true

# on_update:
#   type: "on_update"
#   executed: false
#   shouldRender: false
#   config: "on_update"
#   nextRequest: status
#   preRequest: "update"
#   isCollapsed: true

status:
  type: "status"
  target: "NP"
  executed: false
  shouldRender: false
  config: "status"
  nextRequest: on_status
  preRequest: "on_confirm"
  isCollapsed: true

on_status:
  type: "on_status"
  executed: false
  shouldRender: false
  config: "on_status"
  nextRequest: null
  preRequest: "status"
  isCollapsed: true
